// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           73
// Async Callback:                       1
// Total number of exported functions:  76

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    entity
    (
        init => init
        upgrade => upgrade
        setLeaderlessMode => set_leaderless_mode_endpoint
        changeVoteTokenLock => change_vote_token_lock_endpoint
        getVersion => version_view
        getTrustedHostAddress => trusted_host_address
        getGovTokenId => gov_token
        getGuardedVoteTokens => guarded_vote_tokens
        isLockingVoteTokens => lock_vote_tokens
        getProposalIdCounter => next_proposal_id
        getProposalNftVotes => proposal_nft_votes
        getWithdrawableVoters => withdrawable_voters
        getWithdrawableProposalIds => withdrawable_proposal_ids
        getWithdrawableVotes => withdrawable_votes
        getLockedVoters => locked_voters
        getLockedVotesProposalIds => locked_votes_proposal_ids
        getLockedVotes => locked_votes
        getQuorum => quorum
        getMinVoteWeight => min_vote_weight
        getMinProposeWeight => min_propose_weight
        getVotingPeriodMinutes => voting_period_in_minutes
        getRestrictedVoteNonces => restricted_vote_nonces
        unlockContractStage => unlock_contract_stage_endpoint
        stageContract => stage_contract_endpoint
        stageContractAndPropose => stage_contract_and_propose_endpoint
        activateContract => activate_contract_endpoint
        getContractStage => get_contract_stage_view
        createRole => create_role_endpoint
        removeRole => remove_role_endpoint
        assignRole => assign_role_endpoint
        unassignRole => unassign_role_endpoint
        createPermission => create_permission_endpoint
        createPolicyWeighted => create_policy_weighted_endpoint
        createPolicyOne => create_policy_one_endpoint
        createPolicyAll => create_policy_all_endpoint
        createPolicyQuorum => create_policy_quorum_endpoint
        createPolicyMajority => create_policy_majority_endpoint
        getUserRoles => get_user_roles_view
        getPermissions => get_permissions_view
        getPolicies => get_policies_view
        getRoles => roles
        getRoleMemberAmount => roles_member_amount
        hasUserPlugVoted => has_user_plug_voted_view
        getPlug => get_plug_view
        migrateProposalResult => migrate_proposal_result
        legacyProposalWithdrawals => migrate_pending_withdrawals
        changeQuorum => change_quorum_endpoint
        changeMinVoteWeight => change_min_vote_weight_endpoint
        changeMinProposeWeight => change_min_propose_weight_endpoint
        changeVotingPeriodMinutes => change_voting_period_in_minutes_endpoint
        setRestrictedVoteNonces => set_restricted_vote_nonces_endpoint
        setPlug => set_plug_endpoint
        eject => eject_endpoint
        propose => propose_endpoint
        voteFor => vote_for_endpoint
        voteAgainst => vote_against_endpoint
        sign => sign_endpoint
        execute => execute_endpoint
        directExecute => direct_execute_endpoint
        cancelProposal => cancel_proposal_endpoint
        withdraw => withdraw_endpoint
        withdrawAll => withdraw_all_endpoint
        getProposal => get_proposal_view
        getProposalStatus => get_proposal_status_view
        getProposalVotes => get_proposal_votes_view
        getProposalSigners => get_proposal_signers_view
        getProposalSignatureRoleCounts => get_proposal_signature_role_counts_view
        getProposalPollResults => get_proposal_poll_results_view
        initGovToken => init_gov_token_endpoint
        changeGovToken => change_gov_token_endpoint
        removeGovToken => remove_gov_token_endpoint
        issueGovToken => issue_gov_token_endpoint
        setGovTokenLocalRoles => set_gov_token_local_roles_endpoint
        mint => mint_endpoint
        burn => burn_endpoint
    )
}

multiversx_sc_wasm_adapter::async_callback! { entity }
